export const cars = [
  {
    company: "Volkswagen",
    image: "uploads/w.png",
    models: [
      "Golf",
      "Polo",
      "Passat",
      "Tiguan",
      "Arteon",
      "Jetta",
      "ID.4",
      "ID.3",
      "Scirocco",
      "Touran",
      "Sharan",
      "Beetle",
      "Lupo",
      "Up!",
      "Fox",
      "Touareg",
      "T-Roc",
      "T-Cross",
      "Atlas",
      "Taos",
      "Nivus",
      "ID.5",
      "ID.6",
      "ID.7",
      "e-Golf",
      "e-Up!",
      "Vento",
      "Bora",
      "Santana",
      "Caddy",
      "Multivan",
      "Transporter",
      "Caravelle",
      "California",
      "Amarok",
    ],
  },
  {
    company: "BMW",
    image: "uploads/bmw.png",
    models: [
      "1 Series",
      "2 Series",
      "3 Series",
      "4 Series",
      "5 Series",
      "6 Series",
      "7 Series",
      "8 Series",
      "X1",
      "X2",
      "X3",
      "X4",
      "X5",
      "X6",
      "X7",
      "Z4",
      "i3",
      "i4",
      "i5",
      "i7",
      "i8",
      "iX",
      "M2",
      "M3",
      "M4",
      "M5",
      "M8",
      "XM",
    ],
  },
  {
    company: "Bentley",
    image: "uploads/bentley.png",
    models: [
      "Continental GT",
      "Flying Spur",
      "Mulsanne",
      "Bentayga",
      "Continental GT Speed",
      "Continental GT Convertible",
      "Continental GT W12",
      "Continental GT V8",
      "Contincontinental GT Hybrid",
      "Flying Spur V8",
      "Flying Spur Hybrid",
      "Bentley Speed 6",
      "Bentley Arnage",
      "Bentley Brooklands",
    ],
  },
  {
    company: "Rolls-Royce",
    image: "uploads/rollsroyce.png",
    models: [
      "Phantom",
      "Ghost",
      "Cullinan",
      "Dawn",
      "Wraith",
      "Rolls-Royce Sweptail",
      "Spectre",
      "Silver Spur",
      "Silver Shadow",
      "Corniche",
      "Park Ward",
      "Silver Cloud",
      "Rolls-Royce 102EX",
      "Rolls-Royce 103EX",
    ],
  },
  {
    company: "Mercedes-Benz",
    image: "uploads/mercede.png",
    models: [
      "A-Class",
      "B-Class",
      "C-Class",
      "E-Class",
      "S-Class",
      "CLA",
      "CLS",
      "GLA",
      "GLB",
      "GLC",
      "GLE",
      "GLS",
      "G-Class",
      "SLC",
      "SL",
      "AMG GT",
      "EQC",
      "EQA",
      "EQB",
      "EQE",
      "EQS",
      "V-Class",
      "Citan",
      "Vito",
      "Sprinter",
      "Marco Polo",
      "Maybach S-Class",
      "Maybach GLS",
    ],
  },
  {
    company: "Audi",
    image: "uploads/audi.png",
    models: [
      "A1",
      "A3",
      "A4",
      "A5",
      "A6",
      "A7",
      "A8",
      "Q2",
      "Q3",
      "Q4 e-tron",
      "Q5",
      "Q7",
      "Q8",
      "TT",
      "R8",
      "S3",
      "S4",
      "S5",
      "S6",
      "S7",
      "S8",
      "SQ5",
      "SQ7",
      "SQ8",
      "RS 3",
      "RS 4",
      "RS 5",
      "RS 6",
      "RS 7",
      "RS Q3",
      "RS Q8",
      "e-tron",
      "e-tron GT",
    ],
  },
  {
    company: "Porsche",
    image: "uploads/porsche.png",
    models: [
      "911",
      "718 Cayman",
      "718 Boxster",
      "Taycan",
      "Panamera",
      "Macan",
      "Cayenne",
      "918 Spyder",
      "Carrera GT",
    ],
  },
  {
    company: "Opel",
    image: "uploads/opel.png",
    models: [
      "Astra",
      "Corsa",
      "Insignia",
      "Mokka",
      "Crossland",
      "Grandland",
      "Zafira",
      "Combo",
      "Vivaro",
      "Movano",
      "Adam",
      "Karl",
      "Meriva",
      "Ampera",
      "Tigra",
      "Vectra",
      "Agila",
      "Signum",
    ],
  },
  {
    company: "Ford",
    image: "uploads/ford.png",
    models: [
      "Fiesta",
      "Focus",
      "Mondeo",
      "Kuga",
      "Puma",
      "Mustang",
      "EcoSport",
      "S-Max",
      "Galaxy",
      "Ranger",
      "Transit",
      "C-Max",
      "B-Max",
      "Tourneo Connect",
      "Tourneo Custom",
      "F-150",
      "Expedition",
      "Edge",
      "Bronco",
      "Mustang Mach-E",
      "Lincoln Navigator",
      "Lincoln Aviator",
    ],
  },
  {
    company: "Skoda",
    image: "uploads/skoda.png",
    models: [
      "Fabia",
      "Octavia",
      "Superb",
      "Kodiaq",
      "Kamiq",
      "Scala",
      "Enyaq iV",
      "Roomster",
      "Yeti",
      "Rapid",
      "Citigo",
      "Favorit",
      "Felicia",
      "Praktik",
      "Mii",
    ],
  },
  {
    company: "Hyundai",
    image: "uploads/hyundai.png",
    models: [
      "i10",
      "i20",
      "i30",
      "Elantra",
      "Sonata",
      "Tucson",
      "Santa Fe",
      "Palisade",
      "Kona",
      "Nexo",
      "Ioniq",
      "Creta",
      "Venue",
      "Verna",
      "Accent",
      "Staria",
      "Kona Electric",
      "Ioniq 5",
      "Ioniq 6",
      "Stinger",
      "Sonata Hybrid",
      "Tucson Hybrid",
    ],
  },

  {
    company: "BMW Mini",
    image: "uploads/bmw.png",
    models: [
      "Mini Hatch",
      "Mini Clubman",
      "Mini Countryman",
      "Mini Electric",
      "Mini Roadster",
      "Mini Convertible",
      "Mini Paceman",
      "Mini Clubman All4",
      "Mini John Cooper Works",
      "Mini Coupe",
    ],
  },
  {
    company: "Mercedes-Benz Vans",
    image: "uploads/mercede.png",
    models: ["Sprinter", "Vito", "Marco Polo", "Citan"],
  },
  {
    company: "Smart",
    image: "uploads/smart.png",
    models: ["Fortwo", "Forfour", "EQ ForTwo", "EQ ForFour", "Smart Roadster"],
  },
  {
    company: "Volvo",
    image: "uploads/volvo.png",
    models: [
      "S60",
      "S90",
      "V60",
      "V90",
      "XC40",
      "XC60",
      "XC90",
      "V40",
      "V70",
      "S40",
      "C30",
      "C70",
      "S80",
      "XC40 Recharge",
      "XC90 Recharge",
      "V60 Recharge",
      "C40 Recharge",
    ],
  },
  {
    company: "Alfa Romeo",
    image: "uploads/romeo.png",
    models: [
      "Giulia",
      "Stelvio",
      "Giulietta",
      "4C",
      "Mito",
      "Tonale",
      "Spider",
      "Alfa Romeo 8C Competizione",
      "GTV",
      "Alfa Romeo Brera",
    ],
  },
  {
    company: "Volkswagen Commercial Vehicles",
    image: "uploads/commercialvehicle.png",
    models: ["Transporter", "Crafter", "Caddy", "Amarok"],
  },
  {
    company: "Bugatti",
    image: "uploads/buggati.png",
    models: [
      "Chiron",
      "Divo",
      "Bolide",
      "Veyron",
      "Chiron Pur Sport",
      "Chiron Super Sport",
      "Veyron Super Sport",
      "Veyron Grand Sport Vitesse",
      "Bugatti EB110",
      "La Voiture Noire",
    ],
  },
  {
    company: "Maybach",
    image: "uploads/maybach.png",
    models: ["S-Class", "GLS"],
  },
  {
    company: "Audi Sport",
    image: "uploads/audi.png",
    models: ["RS 3", "RS 4", "RS 5", "RS 6", "RS 7", "R8"],
  },
  {
    company: "Lamborghini",
    image: "uploads/lamborghini.png",
    models: [
      "Huracan",
      "Urus",
      "Aventador",
      "Gallardo",
      "Murcielago",
      "Diablo",
      "Countach",
      "Sián",
      "Centenario",
      "Reventón",
      "Miura",
      "Lamborghini Terzo Millennio",
    ],
  },
  {
    company: "Ferrari",
    image: "uploads/ferari.png",
    models: [
      "488",
      "F8",
      "Portofino",
      "Roma",
      "SF90 Stradale",
      "812 Superfast",
      "GTC4Lusso",
      "LaFerrari",
      "California T",
      "F12 Berlinetta",
      "Ferrari 360 Modena",
      "Ferrari 458 Italia",
      "Ferrari 550 Maranello",
      "Ferrari 599 GTB Fiorano",
      "Ferrari Dino",
      "Ferrari Testarossa",
    ],
  },
  {
    company: "Maserati",
    image: "uploads/maserti.png",
    models: [
      "Ghibli",
      "Levante",
      "Quattroporte",
      "GranTurismo",
      "GranCabrio",
      "Alfieri",
      "MC20",
      "Grecale",
      "Trofeo",
    ],
  },
  {
    company: "Jaguar",
    image: "uploads/jaguar.png",
    models: [
      "XE",
      "XF",
      "XJ",
      "F-Pace",
      "E-Pace",
      "I-Pace",
      "F-Type",
      "XK",
      "XK8",
      "F-Type R",
      "F-Type SVR",
      "XJ6",
      "XJ12",
      "S-Type",
      "XE SV Project 8",
      "I-Pace EV400",
    ],
  },
  {
    company: "Land Rover",
    image: "uploads/landrover.png",
    models: [
      "Range Rover",
      "Discovery",
      "Discovery Sport",
      "Defender",
      "Evoque",
      "Velar",
      "Freelander",
      "Range Rover Sport",
      "Range Rover Velar",
      "Range Rover Evoque",
      "Land Rover Defender 90",
      "Land Rover Defender 110",
      "Land Rover Defender 130",
      "Range Rover PHEV",
      "Range Rover SVAutobiography",
      "Land Rover Defender V8",
    ],
  },
  {
    company: "Chevrolet",
    image: "uploads/chevrolet.png",
    models: [
      "Aveo",
      "Cruze",
      "Malibu",
      "Impala",
      "Bolt EV",
      "Equinox",
      "Traverse",
      "Tahoe",
      "Suburban",
      "Blazer",
      "Trax",
      "Colorado",
      "Silverado 1500",
      "Silverado 2500HD",
      "Silverado 3500HD",
      "Camaro",
      "Corvette",
      "Sonic",
      "Chevy Spark",
      "Chevrolet Silverado EV",
    ],
  },
  {
    company: "GMC",
    image: "uploads/gmc.png",
    models: [
      "Sierra 1500",
      "Sierra 2500HD",
      "Sierra 3500HD",
      "Canyon",
      "Terrain",
      "Acadia",
      "Yukon",
      "Yukon XL",
      "Hummer EV",
      "Savana",
      "Canyon AT4",
      "Sierra AT4",
      "Yukon Denali",
      "GMC Sierra Denali",
    ],
  },
  {
    company: "Cadillac",
    image: "uploads/not.png",
    models: [
      "CT4",
      "CT5",
      "CT6",
      "Escalade",
      "XT4",
      "XT5",
      "XT6",
      "Lyriq",
      "ATS",
      "CTS",
      "SRX",
      "XTS",
      "ELR",
      "CTS-V",
      "Escalade ESV",
      "Escalade Hybrid",
      "Cadillac LYRIQ Electric",
    ],
  },
  {
    company: "Chrysler",
    image: "uploads/chrysler.png",
    models: [
      "300",
      "Pacifica",
      "Pacifica Hybrid",
      "Voyager",
      "Saratoga",
      "Aspen",
      "New Yorker",
      "Chrysler Imperial",
      "Chrysler 200",
      "Chrysler Concorde",
      "Chrysler Town & Country",
      "Chrysler LHS",
    ],
  },
  {
    company: "Dodge",
    image: "uploads/dodge.png",
    models: [
      "Charger",
      "Challenger",
      "Durango",
      "Journey",
      "Grand Caravan",
      "Ram 1500",
      "Ram 2500",
      "Ram 3500",
      "Viper",
      "Dakota",
      "Neon",
      "SRT-4",
      "Dodge Dart",
      "Dodge Caliber",
    ],
  },
  {
    company: "RAM",
    image: "uploads/ram.png",
    models: [
      "1500",
      "2500",
      "3500",
      "RAM ProMaster",
      "RAM ProMaster City",
      "RAM 1500 TRX",
      "RAM 2500 Power Wagon",
      "RAM 3500 Dually",
      "RAM Chassis Cab",
      "RAM 1500 Classic",
      "RAM 1500 Electric",
      "RAM Rebel",
      "RAM Limited",
      "RAM Laramie",
    ],
  },
  {
    company: "Subaru",
    image: "uploads/subaru.png",
    models: [
      "Impreza",
      "Legacy",
      "Outback",
      "Forester",
      "Crosstrek",
      "Ascent",
      "WRX",
      "BRZ",
      "STI",
      "Levorg",
      "Tribeca",
      "Impreza WRX",
      "XV",
      "Subaru Solterra",
    ],
  },
  {
    company: "Suzuki",
    image: "uploads/suzuki.png",
    models: [
      "Swift",
      "Vitara",
      "Baleno",
      "S-Cross",
      "Ignis",
      "Celerio",
      "Alto",
      "Jimny",
      "SX4",
      "Kizashi",
      "Grand Vitara",
      "Ertiga",
      "SPLASH",
      "Wagon R",
      "Suzuki Across",
      "Suzuki Jimny Electric",
    ],
  },
  {
    company: "Mitsubishi",
    image: "uploads/mitsubishi.png",
    models: [
      "Lancer",
      "Outlander",
      "Eclipse Cross",
      "ASX",
      "Pajero",
      "L200",
      "Mirage",
      "Galant",
      "Montero",
      "Mitsubishi i-MiEV",
      "Mitsubishi Outlander PHEV",
      "Mitsubishi Triton",
      "Mitsubishi Delica",
      "Mitsubishi Mirage G4",
    ],
  },
  {
    company: "Genesis",
    image: "uploads/genesis.png",
    models: [
      "G70",
      "G80",
      "G90",
      "GV70",
      "GV80",
      "Genesis Coupe",
      "Genesis Electrified G80",
      "Genesis GV60",
      "G70 Shooting Brake",
    ],
  },
  {
    company: "Rivian",
    image: "uploads/rivian.png",
    models: [
      "R1T",
      "R1S",
      "Rivian EDV (Electric Delivery Van)",
      "Rivian R2 (upcoming compact SUV)",
      "Rivian R2T (upcoming compact truck)",
    ],
  },
  {
    company: "Polestar",
    image: "uploads/volvo.png",
    models: [
      "Polestar 1",
      "Polestar 2",
      "Polestar 3 (upcoming SUV)",
      "Polestar 4 (upcoming SUV)",
      "Polestar 5 (upcoming sedan)",
    ],
  },
  {
    company: "SAIC",
    image: "uploads/saic.png",
    models: [
      "MG ZS",
      "MG Hector",
      "MG Gloster",
      "MG Cyberster (upcoming electric sports car)",
      "Baojun 510",
      "Baojun 730",
      "Wuling Hongguang",
      "Wuling Mini EV",
      "Maxus T60",
      "Maxus V80",
      "Maxus EUNIQ 7 (electric MPV)",
      "Roewe RX5",
      "Roewe i6",
      "Roewe Marvel R (electric SUV)",
    ],
  },
  {
    company: "BYD",
    image: "uploads/byd.png",
    models: [
      "Tang",
      "Song",
      "Qin",
      "Yuan",
      "S7",
      "E6",
      "E9",
      "F3",
      "F0",
      "BYD Atto 3",
      "BYD Seal",
      "BYD Dolphin",
      "BYD Han",
      "BYD S2",
      "BYD T3 (electric van)",
      "BYD Yuan Pro (electric SUV)",
      "BYD Song Pro (electric SUV)",
    ],
  },
  {
    company: "Geely",
    image: "uploads/gelly.png",
    models: [
      "Geely Emgrand",
      "Geely Boyue",
      "Geely Atlas",
      "Geely Binrui",
      "Geely Vision",
      "Geely X7",
      "Geely Icon",
      "Geely Geometric C (electric SUV)",
      "Geely Geometry A (electric sedan)",
      "Geely Lynk & Co 01",
      "Geely Lynk & Co 03",
      "Geely Panda Mini",
      "Geely Yuan Pro (electric SUV)",
    ],
  },
  {
    company: "Chery",
    image: "uploads/chery.png",
    models: [
      "Chery Tiggo 2",
      "Chery Tiggo 3",
      "Chery Tiggo 5",
      "Chery Tiggo 7",
      "Chery Tiggo 8",
      "Chery Arrizo 5",
      "Chery Arrizo 7",
      "Chery E5",
      "Chery EQ1 (electric car)",
      "Chery eQ5 (electric SUV)",
      "Chery Tiggo 3x",
      "Chery Tiggo 8 Pro",
      "Chery Tigo 2 Pro",
      "Chery Cheryexeed TXL (electric SUV)",
    ],
  },
  {
    company: "Lucid Motors",
    image: "uploads/luci.png",
    models: [
      "Lucid Air",
      "Lucid Air Pure",
      "Lucid Air Touring",
      "Lucid Air Grand Touring",
      "Lucid Air Dream Edition",
      "Lucid Gravity (upcoming SUV)",
    ],
  },
  {
    company: "Jeep",
    image: "uploads/jeep.png",
    models: [
      "Wrangler",
      "Cherokee",
      "Grand Cherokee",
      "Compass",
      "Renegade",
      "Gladiator",
      "Wagoneer",
      "Grand Wagoneer",
      "Jeep Commander",
      "Jeep Liberty",
      "Jeep Patriot",
      "Jeep Wagoneer EV",
      "Jeep Grand Cherokee 4xe",
      "Jeep Wrangler 4xe",
    ],
  },
  {
    company: "Renault",
    image: "uploads/renault.png",
    models: [
      "Clio",
      "Megane",
      "Captur",
      "Kadjar",
      "Talisman",
      "Koleos",
      "Espace",
      "Scenic",
      "Twizy",
      "Zoe",
      "Duster",
      "Lodgy",
      "Twingo",
      "Alpine A110",
      "Zoe Electric",
      "Kangoo",
      "Kangoo Electric",
      "Master",
      "Trafic",
      "Lutecia",
      "Dokker",
    ],
  },
  {
    company: "Dacia",
    image: "uploads/dacia.png",
    models: [
      "Sandero",
      "Spring Electric",
      "Lodgy",
      "Dokker",
      "Duster",
      "Dokker Van",
      "Lodgy Van",
      "Spring",
      "Jogger",
    ],
  },
  {
    company: "Peugeot",
    image: "uploads/peugueot.png",
    models: [
      "108",
      "208",
      "308",
      "508",
      "3008",
      "5008",
      "Partner",
      "Rifter",
      "Traveller",
      "Expert",
      "Boxer",
      "4007",
      "5008",
      "208 Electric",
      "2008 Electric",
      "Partner Electric",
      "3008 Hybrid",
      "508 Hybrid",
      "e-2008",
      "e-208",
    ],
  },

  {
    company: "Citroën",
    image: "uploads/citroen.png",
    models: [
      "C1",
      "C3",
      "C4",
      "C5",
      "C3 Aircross",
      "C5 Aircross",
      "Berlingo",
      "SpaceTourer",
      "Jumpy",
      "C-Elysée",
      "DS3",
      "DS4",
      "DS7 Crossback",
      "DS9",
      "AMI",
      "C-Zero",
      "Berlingo Electric",
      "C4 Electric",
      "C5 Aircross Hybrid",
      "e-C4",
      "e-Berlingo",
    ],
  },

  {
    company: "Kia",
    image: "uploads/kia.png",
    models: [
      "Picanto",
      "Rio",
      "Ceed",
      "Sportage",
      "Sorento",
      "Stonic",
      "Seltos",
      "Carnival",
      "EV6",
      "Niro",
      "Soul",
      "Forte",
      "Optima",
      "K900",
      "Stinger",
      "Cadenza",
      "Sorrento Hybrid",
      "Niro EV",
      "Soul EV",
    ],
  },
  {
    company: "Honda",
    image: "uploads/honda.png",
    models: [
      "Jazz",
      "City",
      "Civic",
      "Accord",
      "CR-V",
      "Pilot",
      "HR-V",
      "Passport",
      "Ridgeline",
      "Insight",
      "Clarity",
      "Fit",
      "Element",
      "Odyssey",
      "Ridgeline",
      "Crosstour",
      "Element",
      "Legend",
      "Urban EV",
      "Honda e",
    ],
  },
  {
    company: "Fiat",
    image: "uploads/fiat.png",
    models: [
      "Panda",
      "500",
      "Tipo",
      "Punto",
      "Bravo",
      "Doblo",
      "Qubo",
      "Stilo",
      "Freemont",
      "500L",
      "500X",
      "500 Electric",
      "500C",
      "Linea",
      "Palio",
      "Fiorino",
      "Cinquecento",
    ],
  },
  {
    company: "Toyota",
    image: "uploads/toyota.png",
    models: [
      "Yaris",
      "Corolla",
      "Camry",
      "Avalon",
      "Supra",
      "Sienna",
      "RAV4",
      "Highlander",
      "Land Cruiser",
      "Hilux",
      "Fortuner",
      "Innova",
      "C-HR",
      "Venza",
      "Sequoia",
      "Tundra",
      "Tacoma",
      "FJ Cruiser",
      "Matrix",
      "Prius",
      "Prius Prime",
      "Mirai",
      "GR Yaris",
      "GR Supra",
      "RAV4 Prime",
      "Corolla Cross",
      "Vitz",
      "Lexus LS",
      "Lexus RX",
      "Lexus NX",
      "Lexus IS",
    ],
  },
  {
    company: "Nissan",
    image: "uploads/nissan.png",
    models: [
      "Micra",
      "Note",
      "Altima",
      "Maxima",
      "370Z",
      "GT-R",
      "Leaf",
      "Juke",
      "Qashqai",
      "Rogue",
      "Murano",
      "Pathfinder",
      "X-Trail",
      "Navara",
      "Frontier",
      "Titan",
      "Juke",
      "Versa",
      "Sentra",
      "Armada",
      "NV350",
      "NV200",
      "Livina",
      "Teana",
      "March",
      "Lannia",
    ],
  },
  {
    company: "Mazda",
    image: "uploads/mazda.png",
    models: [
      "Mazda2",
      "Mazda3",
      "Mazda6",
      "CX-3",
      "CX-5",
      "CX-9",
      "MX-5 Miata",
      "RX-8",
      "CX-30",
      "Mazda5",
      "Mazda2 Hybrid",
      "Mazda3 Hatchback",
      "Mazda3 Sedan",
      "Mazda6 Wagon",
      "Mazda CX-50",
      "Mazda CX-70",
      "Mazda CX-80",
      "Mazda6 Hybrid",
    ],
  },
  {
    company: "Tesla",
    image: "uploads/tesla.png",
    models: [
      "Model S",
      "Model 3",
      "Model X",
      "Model Y",
      "Cybertruck",
      "Roadster",
      "Semi",
      "Plaid",
    ],
  },
  {
  "company": "Tata Motors",
  "image": "uploads/tata.png",
  "models": [
    "Nexon",
    "Nexon EV",
    "Punch",
    "Harrier",
    "Safari",
    "Altroz",
    "Tiago",
    "Tigor",
    "Tigor EV",
    "Zest",
    "Bolt",
    "Indica",
    "Indigo",
    "Sumo",
    "Nano"
  ]
},
{
  "company": "Mahindra",
  "image": "uploads/mahindra.png",
  "models": [
    "Scorpio",
    "Scorpio-N",
    "Scorpio Classic",
    "Bolero",
    "Bolero Neo",
    "XUV300",
    "XUV400",
    "XUV500",
    "XUV700",
    "Thar",
    "Marazzo",
    "KUV100",
    "Verito",
    "Verito Vibe",
    "eVerito",
    "TUV300",
    "Supro"
  ]
},
{
  "company": "Force Motors",
  "image": "uploads/force.png",
  "models": [
    "Gurkha",
    "Trax Cruiser",
    "Traveller",
    "Trump"
  ]
},
{
  "company": "Ashok Leyland",
  "image": "uploads/ashok.png",
  "models": [
    "Dost",
    "Bada Dost",
    "Partner",
    "Boss",
    "Captain",
    "Ecomet",
    "Stile",
    "AVTR"
  ]
}
];

export const indianRegions = [
  { name: "Andhra Pradesh" },
  { name: "Arunachal Pradesh" },
  { name: "Assam" },
  { name: "Bihar" },
  { name: "Chhattisgarh" },
  { name: "Goa" },
  { name: "Gujarat" },
  { name: "Haryana" },
  { name: "Himachal Pradesh" },
  { name: "Jharkhand" },
  { name: "Karnataka" },
  { name: "Kerala" },
  { name: "Madhya Pradesh" },
  { name: "Maharashtra" },
  { name: "Manipur" },
  { name: "Meghalaya" },
  { name: "Mizoram" },
  { name: "Nagaland" },
  { name: "Odisha" },
  { name: "Punjab" },
  { name: "Rajasthan" },
  { name: "Sikkim" },
  { name: "Tamil Nadu" },
  { name: "Telangana" },
  { name: "Tripura" },
  { name: "Uttar Pradesh" },
  { name: "Uttarakhand" },
  { name: "West Bengal" },
  { name: "Andaman and Nicobar Islands" },
  { name: "Chandigarh" },
  { name: "Dadra and Nagar Haveli and Daman and Diu" },
  { name: "Lakshadweep" },
  { name: "Delhi" },
  { name: "Puducherry" },
  { name: "Ladakh" },
  { name: "Lakshadweep" },
];

export const bikes = [
  {
    company: "KTM",
    image: "uploads/ktm.png",
    models: [
      "50 SX",
      "65 SX",
      "85 SX",
      "125 SX",
      "250 SX",
      "250 SX-F",
      "350 SX-F",
      "450 SX-F",
      "250 EXC",
      "300 EXC",
      "350 EXC-F",
      "500 EXC-F",
      "690 Enduro R",
      "390 Adventure",
      "790 Adventure",
      "890 Adventure",
      "1290 Super Adventure R",
      "1290 Super Adventure S",
      "125 Duke",
      "200 Duke",
      "390 Duke",
      "790 Duke",
      "890 Duke R",
      "1290 Super Duke R",
      "RC 125",
      "RC 200",
      "RC 390",
      "RC 8C",
      "Freeride E-XC",
      "SX-E 5",
      "300 XC-W",
      "450 Rally",
      "250 XC-F",
    ],
  },
  {
    company: "Moto Guzzi",
    image: "uploads/motoguzzi.png",
    models: [
      "V7",
      "V9",
      "California Touring",
      "California Custom",
      "Griso",
      "Audace",
      "Eldorado",
      "MGX-21",
      "Briar",
      "V85 TT",
      "V100 Mandello",
      "Le Mans",
      "Norge",
      "Stelvio",
      "T3",
      "G5",
      "Spada",
      "S3",
      "Falcone",
      "Lario",
      "Dingo",
      "Gambalunga",
    ],
  },
  {
    company: "Aprilia",
    image: "uploads/aprilia.png",
    models: [
      "RS 125",
      "RS 250",
      "RSV4",
      "Tuono V4",
      "Tuono 660",
      "RS 660",
      "Shiver 900",
      "Dorsoduro 900",
      "Tuareg 660",
      "SX 125",
      "RX 125",
      "Caponord 1200",
      "Pegaso 650",
      "Atlantic 500",
      "Mana 850",
      "Sportcity",
      "SR 50",
      "SR 125",
      "RXV 450",
      "RXV 550",
      "MXV 450",
      "RST 1000 Futura",
      "Beverly 300",
      "Leonardo 125",
      "Mille",
      "Rsv Mille R",
    ],
  },
  {
    company: "Royal Enfield",
    image: "uploads/royal_enfield.png",
    models: [
      "Bullet 350",
      "Bullet 500",
      "Classic 350",
      "Classic 500",
      "Meteor 350",
      "Interceptor 650",
      "Continental GT 650",
      "Thunderbird X",
      "Thunderbird X 500",
      "Himalayan",
      "Hunter 350",
      "Royal Enfield Scram 411",
      "Electra X",
      "Battle Green",
      "Trials",
      "Squadron Red",
      "Classic Signals",
      "BULLET X",
      "Bullet X 500",
      "Cruiser 500",
    ],
  },
  {
    company: "MV Agusta",
    image: "uploads/mv.png",
    models: [
      "F3 675",
      "F3 800",
      "F4",
      "F4 RC",
      "F4 R",
      "Dragster 800",
      "Brutale 800",
      "Brutale 1000",
      "Superveloce 800",
      "Superveloce 75th",
      "Rush 1000",
      "Turismo Veloce 800",
      "Turismo Veloce 1000",
      "Reparto Corse",
      "Stradale 800",
      "B3 800",
      "RVS #1",
      "MV Agusta 1000",
      "Senna",
    ],
  },
  {
    company: "Husqvarna Motorcycles",
    image: "uploads/h.png",
    models: [
      "FC 250",
      "FC 350",
      "FC 450",
      "FE 250",
      "FE 350",
      "FE 450",
      "FE 501",
      "FX 350",
      "FX 450",
      "TE 150i",
      "TE 250i",
      "TE 300i",
      "TE 300",
      "TE 400",
      "TE 500",
      "Vitpilen 701",
      "Svartpilen 701",
      "Vitpilen 401",
      "Svartpilen 401",
      "Norden 901",
      "410",
      "250 WR",
      "501 VITPILEN",
      "701 Enduro",
      "701 Supermoto",
      "701 LR",
      "701 Adventure",
      "TR 650",
    ],
  },
  {
    company: "Benelli",
    image: "uploads/beneli.png",
    models: [
      "TNT 125",
      "TNT 300",
      "TNT 600i",
      "TNT 899",
      "TNT R",
      "TNT 1130",
      "Leoncino 500",
      "Leoncino 800",
      "TRK 502",
      "TRK 502X",
      "TRK 800",
      "Imperiale 400",
      "Imperiale 500",
      "Pepe 50",
      "Benelli 752S",
      "Benelli 302S",
      "Benelli 402S",
      "Zafferano 250",
      "Caffenero 250",
      "Benelli BJ 600",
      "Benelli 600i",
      "Benelli 150",
    ],
  },
  {
    company: "BSA",
    image: "uploads/bsa.png",
    models: [
      "BSA Gold Star",
      "BSA A10",
      "BSA A7",
      "BSA Lightning",
      "BSA C15",
      "BSA Bantam",
      "BSA Rocket Gold Star",
      "BSA M20",
      "BSA M21",
      "BSA Victor 441",
      "BSA B44",
      "BSA Thunderbolt",
      "BSA B33",
      "BSA B40",
      "BSA C12",
      "BSA Dandy",
      "BSA Spitfire Scrambler",
      "BSA Starfire",
      "BSA C25",
    ],
  },
  {
    company: "Norton Motorcycles",
    image: "uploads/norton.png",
    models: [
      "Commando 961",
      "Commando 961 Cafe Racer",
      "Commando 961 Sport",
      "Commando 961 SF",
      "V4 RR",
      "V4 SS",
      "Atlas 650",
      "Norton 850",
      "DominatoR",
      "Norton 961 Café Racer",
      "Norton 650 Atlas Ranger",
      "Norton 650 Atlas Nomad",
      "Norton Electra",
      "Norton Dominator",
      "Norton 500",
      "Manx 500",
      "Norton 16H",
      "Norton 30M",
      "Norton 16H MkII",
      "Norton 600T",
    ],
  },
  {
    company: "Zero Motorcycles (Electric)",
    image: "uploads/zero.png",
    models: [
      "Zero S",
      "Zero SR",
      "Zero SR/F",
      "Zero SR/S",
      "Zero DS",
      "Zero DSR",
      "Zero DSR/X",
      "Zero FX",
      "Zero FXS",
      "Zero FXE",
      "Zero MX",
      "Zero MXR",
      "Zero FXR",
      "Zero S ZF7.2",
      "Zero S ZF14.4",
      "Zero SR ZF14.4",
      "Zero DS ZF14.4",
      "Zero DSR ZF14.4",
      "Zero S R",
    ],
  },
  {
    company: "Victory Motorcycles",
    image: "uploads/victory.png",
    models: [
      "Vegas",
      "Hammer",
      "Kingpin",
      "Cross Country",
      "Cross Roads",
      "Vision",
      "Judge",
      "Octane",
      "High Ball",
      "Gunner",
      "Empulse TT",
    ],
  },
  {
    company: "Indian Motorcycles",
    image: "uploads/indian_motorcycle.png",
    models: [
      "Scout",
      "Scout Bobber",
      "Chief",
      "Chief Vintage",
      "Chief Dark Horse",
      "Chieftain",
      "Chieftain Dark Horse",
      "Chieftain Limited",
      "Roadmaster",
      "Roadmaster Dark Horse",
      "Roadmaster Limited",
      "Pursuit",
      "Indian Springfield",
      "Indian Springfield Dark Horse",
      "FTR 1200",
      "FTR 1200 S",
      "FTR Rally",
      "Indian Motorcycle Scout Sixty",
      "Indian Chief Classic",
      "Indian Chief Custom",
    ],
  },
  {
    company: "Ultraviolette Automotive",
    image: "uploads/ultraviolette.png",
    models: ["F77", "F77 Recon", "F77 Limited"],
  },
  {
    company: "Bajaj Auto",
    image: "uploads/bajaj.png",
    models: [
      "Pulsar N125",
      "Pulsar N150",
      "Pulsar N160",
      "Pulsar N250",
      "Pulsar NS125",
      "Pulsar NS160",
      "Pulsar NS200",
      "Pulsar RS200",
      "Pulsar F250",
      "Dominar 250",
      "Dominar 400",
      "Avenger Street 160",
      "Avenger Street 220",
      "CT 100",
      "CT 110",
      "CT 125X",
      "Platina 100",
      "Platina 110",
      "Platina 125",
      "Discover 100",
      "Discover 110",
      "Discover 125",
      "Discover 135",
      "Discover 150",
      "Discover 100M",
      "Discover 100T",
      "Discover 125M",
      "Discover 125T",
      "Discover 125ST",
      "Discover 150S",
      "Discover 150F",
      "XCD 125",
      "XCD 135",
      "Boxer BM150",
      "Boxer 100",
      "Boxer 125 HD",
      "Boxer 125 X",
      "Avenger 180",
      "Avenger 200",
      "Avenger Street 150",
      "Avenger Street 180",
      "Kawasaki 4S Champion 100",
      "Kawasaki Aspire 110",
      "Kawasaki Boxer 100",
      "Kawasaki Boxer AT 100",
      "Kawasaki Boxer AR 100",
      "Kawasaki Boxer CT 100",
      "Kawasaki Caliber 110",
      "Kawasaki Caliber 115",
      "Kawasaki Caliber Croma 110",
      "Kawasaki Eliminator 175",
      "Kawasaki KB100",
      "Kawasaki KB125",
      "Kawasaki Wind 125",
    ],
  },
  {
    company: "Hero MotoCorp",
    image: "uploads/hero.png",
    models: [
      "Splendor Plus",
      "Splendor Plus XTEC",
      "Super Splendor",
      "Super Splendor XTEC",
      "Glamour",
      "Glamour XTEC",
      "Glamour XTEC Disc",
      "Passion Pro",
      "Passion Pro XTEC",
      "HF Deluxe",
      "HF Deluxe i3S",
      "HF 100",
      "Xtreme 125R",
      "Xtreme 160R",
      "Xtreme 160R 4V",
      "Xtreme 200S",
      "Xtreme 250R",
      "XPulse 200",
      "XPulse 200T",
      "XPulse 210",
      "XPulse 421",
      "Karizma XMR",
      "Maestro Edge 110",
      "Maestro Edge 125",
      "Maestro Edge 125 XTEC",
      "Pleasure Plus",
      "Pleasure Plus XTEC",
      "Destini 125",
      "Destini 125 XTEC",
      "Xoom 110",
      "Xoom 125",
      "Xoom 125 XTEC",
    ],
  },
  {
    company: "TVS Motor Company",
    image: "uploads/tvs.png",
    models: [
      "Apache RTR 160",
      "Apache RTR 160 4V",
      "Apache RTR 180",
      "Apache RTR 200 4V",
      "Apache RTR 200 FI E100",
      "Apache RTR 310",
      "Apache RR 310",
      "Ronin",
      "Raider",
      "Radeon",
      "StaR City +",
      "Sport",
      "XL100",
    ],
  },
  {
    company: "Honda Motorcycle",
    image: "uploads/honda.png",
    models: [
      "Activa 6G",
      "Activa 125",
      "Activa e",
      "Activa H-Smart",
      "Dio",
      "Dio DLX",
      "Dio STD",
      "Shine",
      "Shine SP",
      "Shine 100",
      "Livo",
      "Livo Drum",
      "Livo Disc",
      "SP 125",
      "SP 160",
      "SP160 Double Disc",
      "SP160 Single Disc",
      "Hornet 2.0",
      "Hornet 2.0 STD",
      "Hornet 2.0 DLX",
      "NX200",
      "NX200 STD",
      "CBR 650R",
      "CBR 650R STD",
      "CBR 650R E-Clutch",
      "CB 650R",
      "CB 650R STD",
      "CB 650R E-Clutch",
      "CB300F Flex-Fuel",
      "CB300F Flex-Fuel STD",
      "CB300F Flex-Fuel DLX",
      "CBR 300R",
      "CBR 300R STD",
      "CBR 300R DLX",
      "CBR 250R",
      "CBR 250R STD",
      "CBR 250R DLX",
      "CBR 150R",
      "CBR 150R STD",
      "CBR 150R DLX",
      "CBR 1100XX",
      "CBR 1100XX STD",
      "CBR 1100XX DLX",
    ],
  },

  {
    company: "Suzuki Motorcycle",
    image: "uploads/suzuki.png",
    models: [
      "Access 125",
      "Access 125 Ride Connect Edition",
      "Burgman Street 125",
      "Burgman Street 125 Ride Connect Edition",
      "Avenis 125",
      "Avenis 125 Ride Connect Edition",
      "Gixxer",
      "Gixxer SF",
      "Gixxer 250",
      "Gixxer SF 250",
      "Gixxer SF 250 Flex Fuel",
      "V-Strom SX",
      "V-Strom 800DE",
      "Katana",
      "GSX-8R",
      "Hayabusa",
      "GSX-S1000",
      "GSX-S1000GT",
      "GSX-S750",
      "GSX-R1000R",
      "SV650",
      "V-Strom 1050",
      "RM-Z250",
      "RM-Z450",
      "Burgman Electric (Upcoming)",
      "E Access (Upcoming)",
    ],
  },
  {
    company: "Yamaha Motor",
    image: "uploads/yamah.png",
    models: [
      "FZ-X",
      "FZ S Hybrid",
      "FZ S FI Version 4.0",
      "FZ FI Version 3.0",
      "MT-15 Version 2.0",
      "MT-03",
      "R15 V4",
      "R15M",
      "R15S",
      "R3",
      "FZ 25",
      "FZS 25",
      "Aerox 155",
      "Aerox 155 Version S",
      "RayZR 125 Fi",
      "RayZR 125 Fi Hybrid",
      "Fascino 125 Fi",
      "Fascino 125 Fi Hybrid",
    ],
  },
  {
    company: "BMW Motorrad",
    image: "uploads/bmw.png",
    models: [
      "G 310 R",
      "G 310 GS",
      "G 310 RR",
      "S 1000 RR",
      "S 1000 R",
      "S 1000 XR",
      "M 1000 XR",
      "R 1300 GS",
      "R 1300 GS Adventure",
      "F 900 R",
      "F 900 XR",
      "F 900 GS",
      "R 12",
      "R 12 nineT",
      "R 18",
      "R 18 Classic",
      "R 18 Transcontinental",
      "R 18 B",
      "K 1600 GT",
      "K 1600 GTL",
      "K 1600 B",
      "K 1600 Grand America",
      "C 400 GT",
    ],
  },
  {
    company: "Harley-Davidson",
    image: "uploads/harley.png",
    models: [
      "X440",
      "Nightster",
      "Nightster Special",
      "Sportster S",
      "Fat Bob 114",
      "Pan America Special",
      "Fat Boy 114",
      "Heritage 114",
      "Breakout 117",
      "Street Glide",
      "Road Glide",
    ],
  },
  {
    company: "Ola Electric",
    image: "uploads/ola.png",
    models: [
      "S1 X",
      "S1 X Plus",
      "S1 Pro",
      "S1 Pro Plus",
      "S1 Air",
      "S1 Z",
      "Gig",
      "Roadster X",
      "Roadster X+",
    ],
  },
  {
    company: "Ather Energy",
    image: "uploads/ather.png",
    models: [
      "Ather 450",
      "Ather 450X",
      "Ather 450S",
      "Ather 450 Apex",
      "Ather Rizta",
    ],
  },
  {
    company: "Revolt Motors",
    image: "uploads/revolt.png",
    models: ["RV1", "RV1+", "RV BlazeX", "RV400", "RV400 BRZ"],
  },
  {
    company: "Oben Electric",
    image: "uploads/oben.png",
    models: [
      "Rorr EZ",
      "Rorr EZ (2.6 kWh)",
      "Rorr EZ (3.4 kWh)",
      "Rorr EZ (4.4 kWh)",
      "Rorr STD",
    ],
  },
  {
    company: "Tork Motors",
    image: "uploads/tork.png",
    models: ["Kratos", "Kratos R", "Kratos R Urban"],
  },
  {
    company: "Emflux Motors",
    image: "uploads/emflux.png",
    models: ["Emflux One", "Emflux Two"],
  },
  {
  "company": "Mahindra Two Wheelers",
  "image": "uploads/mahindra.png",
  "models": [
    "Centuro",
    "Gusto",
    "Rodeo",
    "Duro",
    "Pantero",
    "Flyte"
  ]
},
{
  "company": "Kinetic Engineering",
  "image": "uploads/kinetic.png",
  "models": [
    "Kinetic Honda",
    "Kinetic Nova",
    "Kinetic Zoom",
    "Kinetic Velocity",
    "Kinetic Zing"
  ]
},
{
  "company": "LML",
  "image": "uploads/lml.png",
  "models": [
    "LML Freedom",
    "LML NV",
    "LML Star",
    "LML Adreno",
    "LML Select",
    "LML Vespa"
  ]
}

];
