export const cars = [
      {
        "company": "Volkswagen",
        "image":"uploads/w.png",
        "models": [
          "Golf",
          "Polo",
          "Passat",
          "Tiguan",
          "Arteon",
          "Jetta",
          "ID.4",
          "ID.3",
          "Scirocco",
          "Touran",
          "Sharan",
          "Beetle",
          "Lupo",
          "Up!",
          "Fox",
          "Touareg",
          "T-Roc",
          "T-Cross",
          "Atlas",
          "Taos",
          "Nivus",
          "ID.5",
          "ID.6",
          "ID.7",
          "e-Golf",
          "e-Up!",
          "Vento",
          "Bora",
          "Santana",
          "Caddy",
          "Multivan",
          "Transporter",
          "Caravelle",
          "California",
          "Amarok"
        ]
      },
      {
        "company": "BMW",
        "image":"uploads/bmw.png",
        "models": [
          "1 Series",
          "2 Series",
          "3 Series",
          "4 Series",
          "5 Series",
          "6 Series",
          "7 Series",
          "8 Series",
          "X1",
          "X2",
          "X3",
          "X4",
          "X5",
          "X6",
          "X7",
          "Z4",
          "i3",
          "i4",
          "i5",
          "i7",
          "i8",
          "iX",
          "M2",
          "M3",
          "M4",
          "M5",
          "M8",
          "XM"
        ]
      },      
      {
        "company": "Bentley",
        "image":"uploads/bentley.png",
        "models": [
          "Continental GT",
          "Flying Spur",
          "Mulsanne",
          "Bentayga",
          "Continental GT Speed",
          "Continental GT Convertible",
          "Continental GT W12",
          "Continental GT V8",
          "Contincontinental GT Hybrid",
          "Flying Spur V8",
          "Flying Spur Hybrid",
          "Bentley Speed 6",
          "Bentley Arnage",
          "Bentley Brooklands"
        ]
      },      
      {
        "company": "Rolls-Royce",
        "image":"uploads/rollsroyce.png",
        "models": [
          "Phantom",
          "Ghost",
          "Cullinan",
          "Dawn",
          "Wraith",
          "Rolls-Royce Sweptail",
          "Spectre",
          "Silver Spur",
          "Silver Shadow",
          "Corniche",
          "Park Ward",
          "Silver Cloud",
          "Rolls-Royce 102EX",
          "Rolls-Royce 103EX"
        ]
      },      
      {
        "company": "Mercedes-Benz",
        "image":"uploads/mercede.png",
        "models": [
          "A-Class",
          "B-Class",
          "C-Class",
          "E-Class",
          "S-Class",
          "CLA",
          "CLS",
          "GLA",
          "GLB",
          "GLC",
          "GLE",
          "GLS",
          "G-Class",
          "SLC",
          "SL",
          "AMG GT",
          "EQC",
          "EQA",
          "EQB",
          "EQE",
          "EQS",
          "V-Class",
          "Citan",
          "Vito",
          "Sprinter",
          "Marco Polo",
          "Maybach S-Class",
          "Maybach GLS"
        ]
      },      
      {
        "company": "Audi",
        "image":"uploads/audi.png",
        "models": [
          "A1",
          "A3",
          "A4",
          "A5",
          "A6",
          "A7",
          "A8",
          "Q2",
          "Q3",
          "Q4 e-tron",
          "Q5",
          "Q7",
          "Q8",
          "TT",
          "R8",
          "S3",
          "S4",
          "S5",
          "S6",
          "S7",
          "S8",
          "SQ5",
          "SQ7",
          "SQ8",
          "RS 3",
          "RS 4",
          "RS 5",
          "RS 6",
          "RS 7",
          "RS Q3",
          "RS Q8",
          "e-tron",
          "e-tron GT"
        ]
      },      
      {
        "company": "Porsche",
        "image":"uploads/porsche.png",
        "models": [
          "911",
          "718 Cayman",
          "718 Boxster",
          "Taycan",
          "Panamera",
          "Macan",
          "Cayenne",
          "918 Spyder",
          "Carrera GT"
        ]
      },      
      {
        "company": "Opel",
        "image":"uploads/opel.png",
        "models": [
          "Astra",
          "Corsa",
          "Insignia",
          "Mokka",
          "Crossland",
          "Grandland",
          "Zafira",
          "Combo",
          "Vivaro",
          "Movano",
          "Adam",
          "Karl",
          "Meriva",
          "Ampera",
          "Tigra",
          "Vectra",
          "Agila",
          "Signum"
        ]
      },      
      {
        "company": "Ford",
        "image":"uploads/ford.png",
        "models": [
          "Fiesta",
          "Focus",
          "Mondeo",
          "Kuga",
          "Puma",
          "Mustang",
          "EcoSport",
          "S-Max",
          "Galaxy",
          "Ranger",
          "Transit",
          "C-Max",
          "B-Max",
          "Tourneo Connect",
          "Tourneo Custom",
          "F-150",
          "Expedition",
          "Edge",
          "Bronco",
          "Mustang Mach-E",
          "Lincoln Navigator",
          "Lincoln Aviator"
        ]
      },      
      {
        "company": "Skoda",
        "image":"uploads/skoda.png",
        "models": [
          "Fabia",
          "Octavia",
          "Superb",
          "Kodiaq",
          "Kamiq",
          "Scala",
          "Enyaq iV",
          "Roomster",
          "Yeti",
          "Rapid",
          "Citigo",
          "Favorit",
          "Felicia",
          "Praktik",
          "Mii"
        ]
      },
      {
        "company": "Hyundai",
        "image":"uploads/hyundai.png",
        "models": [
          "i10",
          "i20",
          "i30",
          "Elantra",
          "Sonata",
          "Tucson",
          "Santa Fe",
          "Palisade",
          "Kona",
          "Nexo",
          "Ioniq",
          "Creta",
          "Venue",
          "Verna",
          "Accent",
          "Staria",
          "Kona Electric",
          "Ioniq 5",
          "Ioniq 6",
          "Stinger",
          "Sonata Hybrid",
          "Tucson Hybrid"
        ]
      },
      
      {
        "company": "BMW Mini",
        "image":"uploads/bmw.png",
        "models": [
          "Mini Hatch",
          "Mini Clubman",
          "Mini Countryman",
          "Mini Electric",
          "Mini Roadster",
          "Mini Convertible",
          "Mini Paceman",
          "Mini Clubman All4",
          "Mini John Cooper Works",
          "Mini Coupe"
        ]
      },
      {
        "company": "Mercedes-Benz Vans",
        "image":"uploads/mercede.png",
        "models": [
          "Sprinter",
          "Vito",
          "Marco Polo",
          "Citan"
        ]
      },
      {
        "company": "Smart",
        "image":"uploads/smart.png",
        "models": [
          "Fortwo",
          "Forfour",
          "EQ ForTwo",
          "EQ ForFour",
          "Smart Roadster"
        ]
      },   
      {
        "company": "Volvo",
        "image":"uploads/volvo.png",
        "models": [
          "S60",
          "S90",
          "V60",
          "V90",
          "XC40",
          "XC60",
          "XC90",
          "V40",
          "V70",
          "S40",
          "C30",
          "C70",
          "S80",
          "XC40 Recharge",
          "XC90 Recharge",
          "V60 Recharge",
          "C40 Recharge"
        ]
      },         
      {
        "company": "Alfa Romeo",
        "image":"uploads/romeo.png",
        "models": [
          "Giulia",
          "Stelvio",
          "Giulietta",
          "4C",
          "Mito",
          "Tonale",
          "Spider",
          "Alfa Romeo 8C Competizione",
          "GTV",
          "Alfa Romeo Brera"
        ]
      },      
      {
        "company": "Volkswagen Commercial Vehicles",
        "image":"uploads/commercialvehicle.png",
        "models": [
          "Transporter",
          "Crafter",
          "Caddy",
          "Amarok"
        ]
      },
      {
        "company": "Bugatti",
        "image":"uploads/buggati.png",
        "models": [
          "Chiron",
          "Divo",
          "Bolide",
          "Veyron",
          "Chiron Pur Sport",
          "Chiron Super Sport",
          "Veyron Super Sport",
          "Veyron Grand Sport Vitesse",
          "Bugatti EB110",
          "La Voiture Noire"
        ]
      },      
      {
        "company": "Maybach",
        "image":"uploads/maybach.png",
        "models": [
          "S-Class",
          "GLS"
        ]
      },
      {
        "company": "Audi Sport",
        "image":"uploads/audi.png",
        "models": [
          "RS 3",
          "RS 4",
          "RS 5",
          "RS 6",
          "RS 7",
          "R8"
        ]
      },
      {
        "company": "Lamborghini",
        "image":"uploads/lamborghini.png",
        "models": [
          "Huracan",
          "Urus",
          "Aventador",
          "Gallardo",
          "Murcielago",
          "Diablo",
          "Countach",
          "Sián",
          "Centenario",
          "Reventón",
          "Miura",
          "Lamborghini Terzo Millennio"
        ]
      },
      {
        "company": "Ferrari",
        "image":"uploads/ferari.png",
        "models": [
          "488",
          "F8",
          "Portofino",
          "Roma",
          "SF90 Stradale",
          "812 Superfast",
          "GTC4Lusso",
          "LaFerrari",
          "California T",
          "F12 Berlinetta",
          "Ferrari 360 Modena",
          "Ferrari 458 Italia",
          "Ferrari 550 Maranello",
          "Ferrari 599 GTB Fiorano",
          "Ferrari Dino",
          "Ferrari Testarossa"
        ]
      },      
      {
        "company": "Maserati",
        "image":"uploads/maserti.png",
        "models": [
          "Ghibli",
          "Levante",
          "Quattroporte",
          "GranTurismo",
          "GranCabrio",
          "Alfieri",
          "MC20",
          "Grecale",
          "Trofeo"
        ]
      },      
      {
        "company": "Jaguar",
        "image":"uploads/jaguar.png",
        "models": [
          "XE",
          "XF",
          "XJ",
          "F-Pace",
          "E-Pace",
          "I-Pace",
          "F-Type",
          "XK",
          "XK8",
          "F-Type R",
          "F-Type SVR",
          "XJ6",
          "XJ12",
          "S-Type",
          "XE SV Project 8",
          "I-Pace EV400"
        ]
      },      
      {
        "company": "Land Rover",
        "image":"uploads/landrover.png",
        "models": [
          "Range Rover",
          "Discovery",
          "Discovery Sport",
          "Defender",
          "Evoque",
          "Velar",
          "Freelander",
          "Range Rover Sport",
          "Range Rover Velar",
          "Range Rover Evoque",
          "Land Rover Defender 90",
          "Land Rover Defender 110",
          "Land Rover Defender 130",
          "Range Rover PHEV",
          "Range Rover SVAutobiography",
          "Land Rover Defender V8"
        ]
      },
      {
        "company": "Chevrolet",
        "image":"uploads/chevrolet.png",
        "models": [
          "Aveo",
          "Cruze",
          "Malibu",
          "Impala",
          "Bolt EV",
          "Equinox",
          "Traverse",
          "Tahoe",
          "Suburban",
          "Blazer",
          "Trax",
          "Colorado",
          "Silverado 1500",
          "Silverado 2500HD",
          "Silverado 3500HD",
          "Camaro",
          "Corvette",
          "Sonic",
          "Chevy Spark",
          "Chevrolet Silverado EV"
        ]
      },    
      {
        "company": "GMC",
        "image":"uploads/gmc.png",
        "models": [
          "Sierra 1500",
          "Sierra 2500HD",
          "Sierra 3500HD",
          "Canyon",
          "Terrain",
          "Acadia",
          "Yukon",
          "Yukon XL",
          "Hummer EV",
          "Savana",
          "Canyon AT4",
          "Sierra AT4",
          "Yukon Denali",
          "GMC Sierra Denali"
        ]
      },  
      {
        "company": "Cadillac",
        "image":"uploads/not.png",
        "models": [
          "CT4",
          "CT5",
          "CT6",
          "Escalade",
          "XT4",
          "XT5",
          "XT6",
          "Lyriq",
          "ATS",
          "CTS",
          "SRX",
          "XTS",
          "ELR",
          "CTS-V",
          "Escalade ESV",
          "Escalade Hybrid",
          "Cadillac LYRIQ Electric"
        ]
      },
      {
        "company": "Chrysler",
        "image":"uploads/chrysler.png",
        "models": [
          "300",
          "Pacifica",
          "Pacifica Hybrid",
          "Voyager",
          "Saratoga",
          "Aspen",
          "New Yorker",
          "Chrysler Imperial",
          "Chrysler 200",
          "Chrysler Concorde",
          "Chrysler Town & Country",
          "Chrysler LHS"
        ]
      },     
      {
        "company": "Dodge",
        "image":"uploads/dodge.png",
        "models": [
          
          "Charger",
          "Challenger",
          "Durango",
          "Journey",
          "Grand Caravan",
          "Ram 1500",
          "Ram 2500",
          "Ram 3500",
          "Viper",
          "Dakota",
          "Neon",
          "SRT-4",
          "Dodge Dart",
          "Dodge Caliber"
        ]
      },     
      {
        "company": "RAM",
        "image":"uploads/ram.png",
        "models": [
          "1500",
          "2500",
          "3500",
          "RAM ProMaster",
          "RAM ProMaster City",
          "RAM 1500 TRX",
          "RAM 2500 Power Wagon",
          "RAM 3500 Dually",
          "RAM Chassis Cab",
          "RAM 1500 Classic",
          "RAM 1500 Electric",
          "RAM Rebel",
          "RAM Limited",
          "RAM Laramie"
        ]
      },   
      {
        "company": "Subaru",
        "image":"uploads/subaru.png",
        "models": [
          "Impreza",
          "Legacy",
          "Outback",
          "Forester",
          "Crosstrek",
          "Ascent",
          "WRX",
          "BRZ",
          "STI",
          "Levorg",
          "Tribeca",
          "Impreza WRX",
          "XV",
          "Subaru Solterra"
        ]
      },   
      {
        "company": "Suzuki",
        "image":"uploads/suzuki.png",
        "models": [
          "Swift",
          "Vitara",
          "Baleno",
          "S-Cross",
          "Ignis",
          "Celerio",
          "Alto",
          "Jimny",
          "SX4",
          "Kizashi",
          "Grand Vitara",
          "Ertiga",
          "SPLASH",
          "Wagon R",
          "Suzuki Across",
          "Suzuki Jimny Electric"
        ]
      },  
      {
        "company": "Mitsubishi",
        "image":"uploads/mitsubishi.png",
        "models": [
          "Lancer",
          "Outlander",
          "Eclipse Cross",
          "ASX",
          "Pajero",
          "L200",
          "Mirage",
          "Galant",
          "Montero",
          "Mitsubishi i-MiEV",
          "Mitsubishi Outlander PHEV",
          "Mitsubishi Triton",
          "Mitsubishi Delica",
          "Mitsubishi Mirage G4"
        ]
      }, 
      {
        "company": "Genesis",
        "image":"uploads/genesis.png",
        "models": [
          "G70",
          "G80",
          "G90",
          "GV70",
          "GV80",
          "Genesis Coupe",
          "Genesis Electrified G80",
          "Genesis GV60",
          "G70 Shooting Brake"
        ]
      },  
      {
        "company": "Rivian",
        "image":"uploads/rivian.png",
        "models": [
          "R1T",
          "R1S",
          "Rivian EDV (Electric Delivery Van)",
          "Rivian R2 (upcoming compact SUV)",
          "Rivian R2T (upcoming compact truck)"
        ]
      },     
      {
        "company": "Polestar",
        "image":"uploads/volvo.png",
        "models": [
          "Polestar 1",
          "Polestar 2",
          "Polestar 3 (upcoming SUV)",
          "Polestar 4 (upcoming SUV)",
          "Polestar 5 (upcoming sedan)"
        ]
      },  
      {
        "company": "SAIC",
        "image":"uploads/saic.png",
        "models": [
          "MG ZS",
          "MG Hector",
          "MG Gloster",
          "MG Cyberster (upcoming electric sports car)",
          "Baojun 510",
          "Baojun 730",
          "Wuling Hongguang",
          "Wuling Mini EV",
          "Maxus T60",
          "Maxus V80",
          "Maxus EUNIQ 7 (electric MPV)",
          "Roewe RX5",
          "Roewe i6",
          "Roewe Marvel R (electric SUV)"
        ]
      },    
      {
        "company": "BYD",
        "image":"uploads/byd.png",
        "models": [
          "Tang",
          "Song",
          "Qin",
          "Yuan",
          "S7",
          "E6",
          "E9",
          "F3",
          "F0",
          "BYD Atto 3",
          "BYD Seal",
          "BYD Dolphin",
          "BYD Han",
          "BYD S2",
          "BYD T3 (electric van)",
          "BYD Yuan Pro (electric SUV)",
          "BYD Song Pro (electric SUV)"
        ]
      },
      {
        "company": "Geely",
        "image":"uploads/gelly.png",
        "models": [
          "Geely Emgrand",
          "Geely Boyue",
          "Geely Atlas",
          "Geely Binrui",
          "Geely Vision",
          "Geely X7",
          "Geely Icon",
          "Geely Geometric C (electric SUV)",
          "Geely Geometry A (electric sedan)",
          "Geely Lynk & Co 01",
          "Geely Lynk & Co 03",
          "Geely Panda Mini",
          "Geely Yuan Pro (electric SUV)"
        ]
      },  
      {
        "company": "Chery",
        "image":"uploads/chery.png",
        "models": [
          "Chery Tiggo 2",
          "Chery Tiggo 3",
          "Chery Tiggo 5",
          "Chery Tiggo 7",
          "Chery Tiggo 8",
          "Chery Arrizo 5",
          "Chery Arrizo 7",
          "Chery E5",
          "Chery EQ1 (electric car)",
          "Chery eQ5 (electric SUV)",
          "Chery Tiggo 3x",
          "Chery Tiggo 8 Pro",
          "Chery Tigo 2 Pro",
          "Chery Cheryexeed TXL (electric SUV)"
        ]
      },                       
      {
        "company": "Lucid Motors",
        "image":"uploads/luci.png",
        "models": [
          "Lucid Air",
          "Lucid Air Pure",
          "Lucid Air Touring",
          "Lucid Air Grand Touring",
          "Lucid Air Dream Edition",
          "Lucid Gravity (upcoming SUV)"
        ]
      },                             
      {
        "company": "Jeep",
        "image":"uploads/jeep.png",
        "models": [
          "Wrangler",
          "Cherokee",
          "Grand Cherokee",
          "Compass",
          "Renegade",
          "Gladiator",
          "Wagoneer",
          "Grand Wagoneer",
          "Jeep Commander",
          "Jeep Liberty",
          "Jeep Patriot",
          "Jeep Wagoneer EV",
          "Jeep Grand Cherokee 4xe",
          "Jeep Wrangler 4xe"
        ]
      },                
      {
        "company": "Renault",
        "image":"uploads/renault.png",
        "models": [
          "Clio",
          "Megane",
          "Captur",
          "Kadjar",
          "Talisman",
          "Koleos",
          "Espace",
          "Scenic",
          "Twizy",
          "Zoe",
          "Duster",
          "Lodgy",
          "Twingo",
          "Alpine A110",
          "Zoe Electric",
          "Kangoo",
          "Kangoo Electric",
          "Master",
          "Trafic",
          "Lutecia",
          "Dokker"
        ]
      },
      {
        "company": "Dacia",
        "image":"uploads/dacia.png",
        "models": [
          "Sandero",
          "Spring Electric",
          "Lodgy",
          "Dokker",
          "Duster",
          "Dokker Van",
          "Lodgy Van",
          "Spring",
          "Jogger"
        ]
      },      
      {
        "company": "Peugeot",
        "image":"uploads/peugueot.png",
        "models": [
          "108",
          "208",
          "308",
          "508",
          "3008",
          "5008",
          "Partner",
          "Rifter",
          "Traveller",
          "Expert",
          "Boxer",
          "4007",
          "5008",
          "208 Electric",
          "2008 Electric",
          "Partner Electric",
          "3008 Hybrid",
          "508 Hybrid",
          "e-2008",
          "e-208"
        ]
      },
      
      {
        "company": "Citroën",
        "image":"uploads/citroen.png",
        "models": [
          "C1",
          "C3",
          "C4",
          "C5",
          "C3 Aircross",
          "C5 Aircross",
          "Berlingo",
          "SpaceTourer",
          "Jumpy",
          "C-Elysée",
          "DS3",
          "DS4",
          "DS7 Crossback",
          "DS9",
          "AMI",
          "C-Zero",
          "Berlingo Electric",
          "C4 Electric",
          "C5 Aircross Hybrid",
          "e-C4",
          "e-Berlingo"
        ]
      },
      
      {
        "company": "Kia",
        "image":"uploads/kia.png",
        "models": [
          "Picanto",
          "Rio",
          "Ceed",
          "Sportage",
          "Sorento",
          "Stonic",
          "Seltos",
          "Carnival",
          "EV6",
          "Niro",
          "Soul",
          "Forte",
          "Optima",
          "K900",
          "Stinger",
          "Cadenza",
          "Sorrento Hybrid",
          "Niro EV",
          "Soul EV"
        ]
      },
      {
        "company": "Honda",
        "image":"uploads/honda.png",
        "models": [
          "Jazz",
          "City",
          "Civic",
          "Accord",
          "CR-V",
          "Pilot",
          "HR-V",
          "Passport",
          "Ridgeline",
          "Insight",
          "Clarity",
          "Fit",
          "Element",
          "Odyssey",
          "Ridgeline",
          "Crosstour",
          "Element",
          "Legend",
          "Urban EV",
          "Honda e"
        ]
      },
      {
        "company": "Fiat",
        "image":"uploads/fiat.png",
        "models": [
          "Panda",
          "500",
          "Tipo",
          "Punto",
          "Bravo",
          "Doblo",
          "Qubo",
          "Stilo",
          "Freemont",
          "500L",
          "500X",
          "500 Electric",
          "500C",
          "Linea",
          "Palio",
          "Fiorino",
          "Cinquecento"
        ]
      },      
      {
        "company": "Toyota",
        "image":"uploads/toyota.png",
        "models": [
          "Yaris",
          "Corolla",
          "Camry",
          "Avalon",
          "Supra",
          "Sienna",
          "RAV4",
          "Highlander",
          "Land Cruiser",
          "Hilux",
          "Fortuner",
          "Innova",
          "C-HR",
          "Venza",
          "Sequoia",
          "Tundra",
          "Tacoma",
          "FJ Cruiser",
          "Matrix",
          "Prius",
          "Prius Prime",
          "Mirai",
          "GR Yaris",
          "GR Supra",
          "RAV4 Prime",
          "Corolla Cross",
          "Vitz",
          "Lexus LS",
          "Lexus RX",
          "Lexus NX",
          "Lexus IS"
        ]
      },
      {
        "company": "Nissan",
        "image":"uploads/nissan.png",
        "models": [
          "Micra",
          "Note",
          "Altima",
          "Maxima",
          "370Z",
          "GT-R",
          "Leaf",
          "Juke",
          "Qashqai",
          "Rogue",
          "Murano",
          "Pathfinder",
          "X-Trail",
          "Navara",
          "Frontier",
          "Titan",
          "Juke",
          "Versa",
          "Sentra",
          "Armada",
          "NV350",
          "NV200",
          "Livina",
          "Teana",
          "March",
          "Lannia"
        ]
      },
      {
        "company": "Mazda",
        "image":"uploads/mazda.png",
        "models": [
          "Mazda2",
          "Mazda3",
          "Mazda6",
          "CX-3",
          "CX-5",
          "CX-9",
          "MX-5 Miata",
          "RX-8",
          "CX-30",
          "Mazda5",
          "Mazda2 Hybrid",
          "Mazda3 Hatchback",
          "Mazda3 Sedan",
          "Mazda6 Wagon",
          "Mazda CX-50",
          "Mazda CX-70",
          "Mazda CX-80",
          "Mazda6 Hybrid"
        ]
      },
      {
        "company": "Tesla",
        "image":"uploads/tesla.png",
        "models": [
          "Model S",
          "Model 3",
          "Model X",
          "Model Y",
          "Cybertruck",
          "Roadster",
          "Semi",
          "Plaid"
        ]
      }
      
    ]
  
export const indianRegions = [
    { name: "Andhra Pradesh" },
    { name: "Arunachal Pradesh" },
    { name: "Assam" },
    { name: "Bihar" },
    { name: "Chhattisgarh" },
    { name: "Goa" },
    { name: "Gujarat" },
    { name: "Haryana" },
    { name: "Himachal Pradesh" },
    { name: "Jharkhand" },
    { name: "Karnataka" },
    { name: "Kerala" },
    { name: "Madhya Pradesh" },
    { name: "Maharashtra" },
    { name: "Manipur" },
    { name: "Meghalaya" },
    { name: "Mizoram" },
    { name: "Nagaland" },
    { name: "Odisha" },
    { name: "Punjab" },
    { name: "Rajasthan" },
    { name: "Sikkim" },
    { name: "Tamil Nadu" },
    { name: "Telangana" },
    { name: "Tripura" },
    { name: "Uttar Pradesh" },
    { name: "Uttarakhand" },
    { name: "West Bengal" },
    { name: "Andaman and Nicobar Islands" },
    { name: "Chandigarh" },
    { name: "Dadra and Nagar Haveli and Daman and Diu" },
    { name: "Lakshadweep" },
    { name: "Delhi" },
    { name: "Puducherry" },
    { name: "Ladakh" },
    { name: "Lakshadweep" }
  ];
  